### ISSUE TITLE
Menu does not disappear on mobile after being used

### ISSUE THREAD

**Issue by elwincheng** [chavez897/knowquest-capstone#33]
## Expected Behavior

The menu should disappear after a link has been clicked

## Current Behavior

The menu does not disappear after a link has been clicked

## Steps to Reproduce

1. Go on mobile
2. Click on the menu button
3.
4.

## Context (Environment)

The menu blocks a large portion of the display. The user has to scroll down to see page content.

**Comment by elwincheng** [comment]
Can I work on this issue? @pallavbanik111

**Comment by ghost** [comment]
Hi Elwin,

For sure, will just confirm with my team once and get back to you if that's
okay? I'll reach out as soon as possible. Thank you!

Best regards,
Pallav Banik

**Comment by ghost** [comment]
Hey Elwin,

Hope you've had a great weekend! Just wanted to check in, is everything
okay?

Best regards,
Pallav Banik

**Comment by elwincheng** [comment]
Hey Pallav,

I'm doing well

Best regards,
Elwin Cheng

**Comment by ghost** [comment]
Sure, glad to know! Thanks for the update!
